### ISSUE TITLE
why i can't generate the .html file using your CMakelists?

### ISSUE THREAD

**Issue by For-thewin** [PetterS/emscripten_cmake#1]
I use the command line XXX\Emscripten.cmake -G "MinGW Makefiles" XXX. And use mingw32-make, then i just get "my_program.html.exe" not "my_program". Can you tell me the reason? Thanks!

**Comment by PetterS** [comment]
I don't know, sorry. Perhaps something has changed in 5 years?

**Comment by For-thewin** [comment]
All right. Thank you all the same
